blank_issues_enabled: false
contact_links:
  - name: Security Issue (Private)
    url: mailto:efmphone@gmail.com
    about: Please report critical security issues via email
  - name: Discussion
    url: https://github.com/evelynmitchell/sophie/discussions
    about: For general questions and discussions

# Template Configuration
templates:
  - name: Bug Report
    about: Report a bug in Sophie
    template: bug_report.md
    title: "[BUG] "
    labels: ["bug"]
  
  - name: Feature Request
    about: Suggest an idea for Sophie
    template: feature_request.md
    title: "[FEATURE] "
    labels: ["enhancement"]
  
  - name: Task
    about: Create a new development task
    template: task.md
    title: "[TASK] "
    labels: ["task"]
  
  - name: Security Issue
    about: Report a security concern
    template: security_issue.md
    title: "[SECURITY] "
    labels: ["security"]
  
  - name: Documentation Update
    about: Suggest documentation improvements
    template: docs.md
    title: "[DOCS] "
    labels: ["documentation"]