name: CI

on:
  push:
    branches: [ main, ghpages ]
  pull_request:
    branches: [ main ]

jobs:
  generate-lockfile:
    runs-on: ubuntu-latest

    outputs:
      lockfile-exists: ${{ steps.check-lockfile.outputs.exists }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if package-lock.json exists
        id: check-lockfile
        run: |
          if [ -f package-lock.json ]; then
            echo "{exists}={true}" >> $GITHUB_OUTPUT
          else
            echo "{exists}={false}" >> $GITHUB_OUTPUT
          fi

      - name: Set up Node.js
        if: steps.check-lockfile.outputs.exists == 'false'
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies and generate package-lock.json
        if: steps.check-lockfile.outputs.exists == 'false'
        run: npm install

      - name: Commit and push package-lock.json
        if: steps.check-lockfile.outputs.exists == 'false'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add package-lock.json
          git commit -m 'Generate package-lock.json' || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: generate-lockfile

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install gh-pages to bundle for static 
      run: npm install gh-pages --save-dev
    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build
      run: npm run build

    - name: Start server
      run: npm start &

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
